[package]
name = "anagram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is_anagram = "0.1.0"
itertools = "0.10.5"
primal = "0.3.2"
rstest = "0.17.0"

[dev-dependencies]

